// UOMapVibe — Main app: Leaflet setup with UO coordinate system
window.UOMapVibe = window.UOMapVibe || {};

(function () {
    'use strict';

    // UO Map 0 (Felucca) dimensions
    const MAP_WIDTH = 7168;
    const MAP_HEIGHT = 4096;
    const MAX_ZOOM = 5;

    // Leaflet with Simple CRS — pixel coordinates
    const map = L.map('map', {
        crs: L.CRS.Simple,
        minZoom: 0,
        maxZoom: MAX_ZOOM,
        zoomControl: true,
        attributionControl: false
    });

    // Bounds: UO origin is top-left, X=east, Y=south
    // In Leaflet Simple CRS: [lat, lng] = [y, x] but Y is inverted
    // We map UO coords so that (0,0) is top-left
    const bounds = L.latLngBounds(
        L.latLng(-MAP_HEIGHT, 0),       // south-west (bottom-left)
        L.latLng(0, MAP_WIDTH)          // north-east (top-right)
    );

    map.setMaxBounds(bounds.pad(0.1));
    map.fitBounds(bounds);

    // Tile layer — tiles generated by TileExporter at tiles/{z}/{x}/{y}.bmp
    L.tileLayer('tiles/{z}/{x}/{y}.bmp', {
        minZoom: 0,
        maxZoom: MAX_ZOOM,
        bounds: bounds,
        noWrap: true,
        tileSize: 256,
        errorTileUrl: '' // hide missing tiles silently
    }).addTo(map);

    // Coordinate display
    map.on('mousemove', function (e) {
        const uoX = Math.floor(e.latlng.lng);
        const uoY = Math.floor(-e.latlng.lat);
        document.getElementById('coords').textContent = `X: ${uoX}, Y: ${uoY}`;
    });

    // Convert UO world coords to Leaflet latLng
    function uoToLatLng(uoX, uoY) {
        return L.latLng(-uoY, uoX);
    }

    // Convert Leaflet latLng to UO world coords
    function latLngToUO(latLng) {
        return {
            x: Math.floor(latLng.lng),
            y: Math.floor(-latLng.lat)
        };
    }

    // Convert Leaflet bounds to UO bounding box
    function boundsToUO(bounds) {
        const sw = latLngToUO(bounds.getSouthWest());
        const ne = latLngToUO(bounds.getNorthEast());
        return {
            x1: Math.min(sw.x, ne.x),
            y1: Math.min(sw.y, ne.y),
            x2: Math.max(sw.x, ne.x),
            y2: Math.max(sw.y, ne.y)
        };
    }

    // Status message helper
    function setStatus(msg) {
        document.getElementById('status-msg').textContent = msg;
    }

    // Expose globals
    UOMapVibe.map = map;
    UOMapVibe.uoToLatLng = uoToLatLng;
    UOMapVibe.latLngToUO = latLngToUO;
    UOMapVibe.boundsToUO = boundsToUO;
    UOMapVibe.setStatus = setStatus;
    UOMapVibe.MAP_WIDTH = MAP_WIDTH;
    UOMapVibe.MAP_HEIGHT = MAP_HEIGHT;

    // Navigate to Britain Bank by default
    map.setView(uoToLatLng(1438, 1690), 3);
})();
